Djent Hero Collection + similar, Paradigm
YARC-Official/OpenSource pull request #18
Opened 2023-07-19 14:36 UTC by yoitsOJ

-Djent Hero Collection
-Djent Hero
-Djent Hero DLC

-Paradigm

All icons by me

2023-07-19 14:45 UTC, kaduwaengertner requested changes
For the first ones I'm not a big fan of the rotation they have, I saw that the original one doesn't have that so might be better to just make it without it and also removing the rounded parts of the mask 
![image](https://github.com/YARC-Official/OpenSource/assets/87105274/80f01d11-1e39-42ab-9296-f99ade9e0b0c)

I think for this icon we can adjust the bottom line of the circle, the icon feels too big, scaling down a bit would help with the bottom part also
![image](https://github.com/YARC-Official/OpenSource/assets/87105274/796c8ab2-5714-47ea-beeb-f528d6e73b46)

2023-07-19 14:47 UTC, yoitsOJ commented
Alright I can make those edits, should take 10-20 minutes

2023-07-19 15:48 UTC, yoitsOJ reviewed
- Removed text tilt in DHC icons
- Shrunk paradigm in Paradigm icon
- Cleaned up ring masks

2023-07-23 17:15 UTC, kaduwaengertner approved these changes

2023-07-23 17:53 UTC, merged