Add Lisarb icons
YARC-Official/OpenSource pull request #38
Opened 2023-08-12 23:16 UTC by lucaspontoexe

Icons for @naonemeu's Lisarb setlists

2023-08-12 23:23 UTC, kaduwaengertner requested changes
Just need adjust on this cuts 
![image](https://github.com/YARC-Official/OpenSource/assets/87105274/8d47dc4c-8e12-4453-9fb0-28b4e8403fdc)

![image](https://github.com/YARC-Official/OpenSource/assets/87105274/6d4f21ff-da27-4ad8-92a4-8aaa9be9c0c3)

2023-08-13 00:03 UTC, lucaspontoexe commented
Done - they were a bit tricky to get them right

2023-08-13 00:04 UTC, kaduwaengertner commented
Approved on my end! Just need to wait for EA to merge

2023-08-13 00:05 UTC, kaduwaengertner approved these changes

2023-08-13 01:30 UTC, merged